<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.3.2.295
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@zeq.com',
		'to' => 'info@zeq.com'
	),
	'fields' => array(
		'custom_U2694' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => '',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'\' is required.',
				'format' => 'Field \'\' has an invalid email.'
			)
		),
		'custom_U2704' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'\' is required.'
			)
		)
	)
);

process_form($form);
?>
